export const TIME_COMPLEXITY_OPTIONS = [
  { value: 'O(1)', label: 'O(1) - Constant Time' },
  { value: 'O(log N)', label: 'O(log N) - Logarithmic Time' },
  { value: 'O(√N)', label: 'O(√N) - Square Root Time' },
  { value: 'O(N)', label: 'O(N) - Linear Time' },
  { value: 'O(N log N)', label: 'O(N log N) - Linearithmic Time' },
  { value: 'O(N * M)', label: 'O(N * M) - Dual Input Matrix/Grid Time' },
  { value: 'O(N * K)', label: 'O(N * K) - Linear * Factor Time' },
  { value: 'O(N^2)', label: 'O(N^2) - Quadratic Time (Nested Loops)' },
  { value: 'O(N^3)', label: 'O(N^3) - Cubic Time (Triple Loops)' },
  { value: 'O(2^N)', label: 'O(2^N) - Exponential Time (Subsets)' },
  { value: 'O(2^N * N)', label: 'O(2^N * N) - Bitmask DP / Subsets Time' },
  { value: 'O(N!)', label: 'O(N!) - Factorial Time (Permutations)' },
  { value: 'O(V + E)', label: 'O(V + E) - Graph BFS / DFS Traversal Time' },
  { value: 'O(E log V)', label: 'O(E log V) - Dijkstra / Shortest Path Time' },
  { value: 'O(V^2)', label: 'O(V^2) - Dense Graph / All-Pairs Time' },
  { value: 'O(V * E)', label: 'O(V * E) - Bellman-Ford Shortest Path Time' },
];

export const SPACE_COMPLEXITY_OPTIONS = [
  { value: 'O(1)', label: 'O(1) - Constant Space (No Extra Memory)' },
  { value: 'O(log N)', label: 'O(log N) - Logarithmic Space (Recursion Call Stack)' },
  { value: 'O(N)', label: 'O(N) - Linear Space (Hash Table / Array)' },
  { value: 'O(N + M)', label: 'O(N + M) - Combined Linear Memory' },
  { value: 'O(N log N)', label: 'O(N log N) - Auxiliary Sorting Memory' },
  { value: 'O(N * M)', label: 'O(N * M) - 2D Grid / Matrix Memory' },
  { value: 'O(N^2)', label: 'O(N^2) - Quadratic 2D Matrix Memory' },
  { value: 'O(2^N)', label: 'O(2^N) - Exponential Recursion Memory' },
  { value: 'O(V + E)', label: 'O(V + E) - Graph Adjacency List Memory' },
  { value: 'O(V)', label: 'O(V) - Graph Visited / Distance Array Memory' },
];
